# -*- coding:utf-8 -*-
# pylint: disable=missing-docstring

OAPI_IGNORE_END_ELEMENTS = [
    "request_id",
    "mac_address",
    "public_ip",
    "keypair_fingerprint",
    "link_date",
    "private_key",
    "private_ip",
    "filter",
    "creation_date",
    "public_dns_name",
    "private_dns_name",
    "dns_name",
    "secret_key",
    "client_gateway_configuration",
    "last_modification_date",
    "upload_date",
    "comment",
    "osu_manifest_url",
    "max_value",
    "file_location",
    "message",
    "ip_ranges",
    "ca_fingerprint",
    "ca_pem",
    "body",
    "chain",
    "orn",
    "last_state_change_date",
    "outside_ip_address",
    "available_ips_count",
    "backend_ips",
    "quota_type",
    "used_value",
    "created_at",
    "updated_at",
    "kubeconfig",
    "private",
    "backend_vm_health",
    # Randomized values
    "bgp_asn",
    "load_balancer_name",
    "load_balancer_names",
    "listener_rule_name",
    "keypair_name",
    "security_group_name",
    "image_name",
    "policy_name",
    "cookie_name",
    "user_group_name",
    "policy_orn",
    "user_name",
    "policy_names",
    "security_group_names",
]

OAPI_IGNORE_TYPE_ELEMENTS = {
    "outscale_net_peering": "expiration_date",
    "outscale_net_peering_acceptation": "expiration_date",
    "outscale_server_certificate": {"name", "expiration_date"},
}

OAPI_ID_PREFIXES = [
    "i",
    "subnet",
    "snap",
    "img",
    "vol",
    "eni",
    "vpc",
    "igw",
    "nat",
    "vgw",
    "pcx",
    "sg",
    "rtb",
    "rtbassoc",
    "vpn",
    "vpcconn",
    "ami",
    "dxvif",
    "vpce",
    "fgpu",
    "aar",
    "ca",
]

OAPI_SERVICE_CONFIG = {
    "ignore_end_elements": OAPI_IGNORE_END_ELEMENTS,
    "ignore_type_elements": OAPI_IGNORE_TYPE_ELEMENTS,
    "id_prefixes": OAPI_ID_PREFIXES,
}
