blank_issues_enabled: false
contact_links:
  - name: 3DS OUTSCALE Provider documentation
    url: https://registry.terraform.io/providers/outscale/outscale/latest/docs/
    about: Official documentation is available on terraform's registry.
