blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Get Help
    url: https://discord.gg/HUVtY5gT6s
    about: Join our Discord server to ask questions and connect with the maintainers.