name: Check build & lint

on:
  pull_request:
    branches: [master]
    paths:
      - "**.go"
      - "go.*"
      - "GNUMakefile"
      - ".github/workflows/build.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: ⬇️ Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "./go.mod"
      - name: 🔎 golangci-lint
        uses: outscale/goutils/.github/actions/lint@05ad7817324ae08f446039cbe11ed0322ae2467b # main
      - name: 🔎 Run make build
        run: make build
        shell: bash
