name: Check build & lint

on:
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "go.*"
      - "GNUMakefile"
      - ".github/workflows/build.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: ⬇️ Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "./go.mod"
      - name: 🔎 golangci-lint
        uses: outscale/goutils/.github/actions/lint@bd54158ec41d8d18182eb99e516353ed5ea92858 # v1.0.1
      - name: 🔎 Run make build
        run: make build
        shell: bash
