name: Check build & lint

on:
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "go.*"
      - "GNUMakefile"
      - ".github/workflows/build.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: ⬇️ Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "./go.mod"
      - name: 🔎 golangci-lint
        uses: outscale/goutils/.github/actions/lint@ba9b0e7bcc1ab4b8fd2c69d8b4de17d86218f5b5 # v1.0.0
      - name: 🔎 Run make build
        run: make build
        shell: bash
