name: Compliance

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Plumber
      uses: outscale/.github/pipeline-compliance@20536b27d3cc42707118eb3411a4393e846ab8f3 # v1.0.1
      with:
        plumber-threshold: 93
        github-token: ${{ secrets.PLUMBER_TOKEN }}
