name: Credential Scanner

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  cred-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Scan credentials
      uses: outscale/cred-scan@main
      with:
        scan_path: "./"
