name: Generate documentation
on:
    workflow_dispatch:
        inputs:
            tag:
                description: "doc template tag repository"
                required: true

permissions:
    contents: read

jobs:
    doc-release:
        environment: auto-build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  submodules: "recursive"
            - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
            - name: auto-generate release
              run: .github/scripts/doc-build.sh
              env:
                  TAG: ${{ github.event.inputs.tag }}
            - name: push release branch
              run: .github/scripts/doc-push.sh
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  TAG: ${{ github.event.inputs.tag }}
            - name: create pull request
              run: .github/scripts/doc-pr.sh
              env:
                  TAG: ${{ github.event.inputs.tag }}
                  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
