name: Local Acceptances tests

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - '**.sum'
      - '**.mod'
      - 'GNUmakefile'
    workflow_dispatch:

jobs:
  Local_acceptances_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5
          terraform_wrapper: false
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: local tests
        run: |
          wget https://github.com/outscale/osc-ricochet-2/releases/download/v0.4.0/osc-ricochet-2_v0.4.0_x86_64-unknown-linux-musl.tar.gz
          tar -xvf osc-ricochet-2_v0.4.0_x86_64-unknown-linux-musl.tar.gz
          ./ricochet-2 ./ricochet.json &
          make test-locally
