name: Nets integration tests

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - 'tests/**'
      - 'scripts/integration.sh'
      - 'GNUmakefile'
      - '!**_test.go'
  workflow_dispatch:

jobs:
  Nets_integration_tests:
    environment: test-us-east-2
    runs-on: [self-hosted, linux, us-east-2]
    steps:
      - uses: actions/checkout@v4
        with:
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            ref: ${{ github.event.pull_request.head.ref }}
      - uses: outscale-dev/frieza-github-actions/frieza-clean@master
        with:
          access_key: ${{ secrets.OSC_ACCESS_KEY }}
          secret_key: ${{ secrets.OSC_SECRET_KEY }}
          region: ${{ secrets.OSC_REGION }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5
          terraform_wrapper: false
      - name: Build go test
        run: make test
        env:
          OUTSCALE_ACCESSKEYID: ${{ secrets.OSC_ACCESS_KEY }}
          OUTSCALE_SECRETKEYID: ${{ secrets.OSC_SECRET_KEY }}
          OUTSCALE_REGION: ${{ secrets.OSC_REGION }}
          OUTSCALE_ACCOUNT: ${{ secrets.OSC_ACCOUNT_ID }}
          OUTSCALE_IMAGEID: ${{ secrets.OUTSCALE_IMAGEID }}
      - name: Run nets integration tests
        run: make test-integration
        env:
          OUTSCALE_ACCESSKEYID: ${{ secrets.OSC_ACCESS_KEY }}
          OUTSCALE_SECRETKEYID: ${{ secrets.OSC_SECRET_KEY }}
          OUTSCALE_REGION: ${{ secrets.OSC_REGION }}
          OUTSCALE_ACCOUNT: ${{ secrets.OSC_ACCOUNT_ID }}
          OUTSCALE_IMAGEID: ${{ secrets.OUTSCALE_IMAGEID }}
          TF_VAR_image_id: ${{ secrets.OUTSCALE_IMAGEID }}
          TF_VAR_region: ${{ secrets.OSC_REGION }}
          TF_VAR_service_name: ${{ secrets.SERVICE_NAME }}
          RUN_NETS_ONLY: ${{ secrets.RUN_NETS_ONLY }}

