name: Reusable Acceptance Test

on:
    workflow_call:
        inputs:
            test-command:
                required: true
                type: string
            region:
                required: true
                type: string
            service:
                required: true
                type: string
            providers:
                required: true
                type: string

permissions:
    contents: read

jobs:
    acceptance-test:
        environment: test-${{ inputs.region }}
        runs-on:
            - self-hosted
            - linux
            - ${{ inputs.region }}
            - ${{ inputs.service }}
        steps:
            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            - uses: outscale/frieza-github-actions/frieza-clean@master
              with:
                  access_key: ${{ secrets.OSC_ACCESS_KEY }}
                  secret_key: ${{ secrets.OSC_SECRET_KEY }}
                  region: ${{ secrets.OSC_REGION }}
                  providers: ${{ inputs.providers }}
            - name: Set up Go
              uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
              with:
                  go-version-file: "./go.mod"
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
              with:
                  terraform_version: 1.14.3
                  terraform_wrapper: false
            - name: Build go test
              run: make test
              env:
                  OUTSCALE_ACCESSKEYID: ${{ secrets.OSC_ACCESS_KEY }}
                  OUTSCALE_SECRETKEYID: ${{ secrets.OSC_SECRET_KEY }}
                  OUTSCALE_REGION: ${{ secrets.OSC_REGION }}
                  OUTSCALE_ACCOUNT: ${{ secrets.OSC_ACCOUNT_ID }}
                  OUTSCALE_IMAGEID: ${{ secrets.OUTSCALE_IMAGEID }}
                  OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
                  OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
                  OSC_REGION: ${{ secrets.OSC_REGION }}
            - name: Run acceptance tests
              run: make ${{ inputs.test-command }}
              env:
                  OUTSCALE_ACCESSKEYID: ${{ secrets.OSC_ACCESS_KEY }}
                  OUTSCALE_SECRETKEYID: ${{ secrets.OSC_SECRET_KEY }}
                  OUTSCALE_REGION: ${{ secrets.OSC_REGION }}
                  OUTSCALE_ACCOUNT: ${{ secrets.OSC_ACCOUNT_ID }}
                  OUTSCALE_IMAGEID: ${{ secrets.OUTSCALE_IMAGEID }}
                  OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
                  OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
                  OSC_REGION: ${{ secrets.OSC_REGION }}
